import { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Grid, Container } from "@mui/material";
import Languages from "components/Languages";
import { LanguageConfig } from "components/Languages/config";
import Header from "components/Header";
import firebaseDb from "../../firebaseConfig";
import { collection, getDocs } from 'firebase/firestore/lite';
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const [languages, setLanguages] = useState([]);
  const getLanguages = async () => {
    const langCol = collection(firebaseDb, "tech-languages");
    const langSnapshot = await getDocs(langCol);
    const langList = langSnapshot.docs.map(doc => doc.data());
    setLanguages(langList);
  }

  useEffect(() => {
    getLanguages();
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container>
        <Grid sx={{flexGrow: 1, marginTop: 2}} container spacing={4}>
          {LanguageConfig.map((config: any) => { 
            const lang = languages.find(lang => lang.id == config.id);
            return (
            <Grid item xs={4} md={3} key={config.name}>
              <Languages
                name={config.name}
                icon={config.icon}
                isActive={config.isActive}
                route={config.route}
                config={lang}
              />
            </Grid>
          )}
          ) }
        </Grid>
      </Container>
      <Grid sx={{ flexGrow: 1 }}>
        <footer>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </Grid>
    </>
  );
};

export default Home;
